const actionTypes = Object.freeze({
    //app
    APP_START_UP_COMPLETE: 'APP_START_UP_COMPLETE',
    SET_CONTENT_OF_CONFIRM_MODAL: 'SET_CONTENT_OF_CONFIRM_MODAL',
    //userDetail
    FETCH_USER_DETAIL_START: 'FETCH_USER_DETAIL_START',
    FETCH_USER_DETAIL_SUCCESS: 'FETCH_USER_DETAIL_SUCCESS',
    FETCH_USER_DETAIL_FAILURE: 'FETCH_USER_DETAIL_FAILURE',
    UPDATE_USER_DETAIL_SUCCESS: 'UPDATE_USER_DETAIL_SUCCESS',
    UPDATE_USER_DETAIL_FAILURE: 'UPDATE_USER_DETAIL_FAILURE',
    //admin
    ADMIN_LOGIN_SUCCESS: 'ADMIN_LOGIN_SUCCESS',
    ADMIN_LOGIN_FAIL: 'ADMIN_LOGIN_FAIL',
    PROCESS_LOGOUT: 'PROCESS_LOGOUT',
    // Địa chỉ người dùng
    FETCH_USER_ADDRESSES_SUCCESS: 'FETCH_USER_ADDRESSES_SUCCESS',
    FETCH_USER_ADDRESSES_FAILURE: 'FETCH_USER_ADDRESSES_FAILURE',
    ADD_USER_ADDRESS_SUCCESS: 'ADD_USER_ADDRESS_SUCCESS',
    ADD_USER_ADDRESS_FAILURE: 'ADD_USER_ADDRESS_FAILURE',

    UPDATE_USER_ADDRESS_SUCCESS: 'UPDATE_USER_ADDRESS_SUCCESS',
    UPDATE_USER_ADDRESS_FAILURE: 'UPDATE_USER_ADDRESS_FAILURE',

    DELETE_USER_ADDRESS_SUCCESS: 'DELETE_USER_ADDRESS_SUCCESS',
    DELETE_USER_ADDRESS_FAILURE: 'DELETE_USER_ADDRESS_FAILURE',

    SET_DEFAULT_ADDRESS_SUCCESS: 'SET_DEFAULT_ADDRESS_SUCCESS',
    SET_DEFAULT_ADDRESS_FAILURE: 'SET_DEFAULT_ADDRESS_FAILURE',
    //user
    FETCH_USERS_START: 'FETCH_USERS_START',
    FETCH_USERS_SUCCESS: 'FETCH_USERS_SUCCESS',
    FETCH_USERS_FAILED: 'FETCH_USERS_FAILED',

    CREATE_USER_SUCCESS: 'CREATE_USER_SUCCESS',
    CREATE_USER_FAILED: 'CREATE_USER_FAILED',

    UPDATE_USER_SUCCESS: 'UPDATE_USER_SUCCESS',
    UPDATE_USER_FAILED: 'UPDATE_USER_FAILED',

    DELETE_USER_SUCCESS: 'DELETE_USER_SUCCESS',
    DELETE_USER_FAILED: 'DELETE_USER_FAILED',
      // Shop actions
  FETCH_SHOPS_START: 'FETCH_SHOPS_START',
  FETCH_SHOPS_SUCCESS: 'FETCH_SHOPS_SUCCESS',
  FETCH_SHOPS_FAILED: 'FETCH_SHOPS_FAILED',
  CREATE_SHOP_SUCCESS: 'CREATE_SHOP_SUCCESS',
  CREATE_SHOP_FAILED: 'CREATE_SHOP_FAILED',
  UPDATE_SHOP_SUCCESS: 'UPDATE_SHOP_SUCCESS',
  UPDATE_SHOP_FAILED: 'UPDATE_SHOP_FAILED',
  DELETE_SHOP_SUCCESS: 'DELETE_SHOP_SUCCESS',
  DELETE_SHOP_FAILED: 'DELETE_SHOP_FAILED',
  APPROVE_SHOP_SUCCESS: 'APPROVE_SHOP_SUCCESS',
  APPROVE_SHOP_FAILED: 'APPROVE_SHOP_FAILED',
  REJECT_SHOP_SUCCESS: 'REJECT_SHOP_SUCCESS',
  REJECT_SHOP_FAILED: 'REJECT_SHOP_FAILED',
})

export default actionTypes;
